#!/bin/bash -x

set -euo pipefail
IFS=$'\n\t'

rm -rf /tmp/FFI-Platypus /tmp/FFI-Build

cpanm -n Dist::Zilla


git clone --depth 2 https://github.com/Perl5-FFI/FFI-Platypus.git /tmp/FFI-Platypus
cd /tmp/FFI-Platypus
dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n
dzil install --install-command 'cpanm -n .'

git clone --depth 2 https://github.com/Perl5-FFI/FFI-Build.git /tmp/FFI-Build
cd /tmp/FFI-Build
dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n
dzil install --install-command 'cpanm -n .'
